repository:
  branch_protection_rules:
    - pattern: main
      required_status_checks:
        strict: true
        contexts:
          - "cpp-format"
          - "markdown-lint"
          - "mermaid-lint"
          - "unit-tests"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      allow_force_pushes: false
      allow_deletions: false
