// GENERATED by scripts/generate_hid_display_table.py — do not edit by hand.
// Re-run the generator after editing scripts/hid_display_data/*.yaml.

import 'package:flutter/material.dart';

/// HID usage page + ID → display descriptor for keystroke chips.
enum KeyCategory {
  letter,
  number,
  navigation,
  edit,
  modifier,
  function,
  punctuation,
  system,
  media,
  locking,
  numpad,
  language,
}

class KeyDisplay {
  const KeyDisplay({
    required this.label,
    required this.category,
    required this.page,
    required this.usageId,
    this.glyph,
    this.icon,
  });

  final String label;
  final KeyCategory category;
  final int page;
  final int usageId;
  final String? glyph;
  final IconData? icon;
}

/// Packed (page << 16) | usageId → display descriptor.
/// Same packing as Flutter's PhysicalKeyboardKey.usbHidUsage.
const Map<int, KeyDisplay> kHidUsageDisplay = {
  0x00070004: KeyDisplay(
      label: 'a', category: KeyCategory.letter, page: 0x07, usageId: 0x04),
  0x00070005: KeyDisplay(
      label: 'b', category: KeyCategory.letter, page: 0x07, usageId: 0x05),
  0x00070006: KeyDisplay(
      label: 'c', category: KeyCategory.letter, page: 0x07, usageId: 0x06),
  0x00070007: KeyDisplay(
      label: 'd', category: KeyCategory.letter, page: 0x07, usageId: 0x07),
  0x00070008: KeyDisplay(
      label: 'e', category: KeyCategory.letter, page: 0x07, usageId: 0x08),
  0x00070009: KeyDisplay(
      label: 'f', category: KeyCategory.letter, page: 0x07, usageId: 0x09),
  0x0007000A: KeyDisplay(
      label: 'g', category: KeyCategory.letter, page: 0x07, usageId: 0x0A),
  0x0007000B: KeyDisplay(
      label: 'h', category: KeyCategory.letter, page: 0x07, usageId: 0x0B),
  0x0007000C: KeyDisplay(
      label: 'i', category: KeyCategory.letter, page: 0x07, usageId: 0x0C),
  0x0007000D: KeyDisplay(
      label: 'j', category: KeyCategory.letter, page: 0x07, usageId: 0x0D),
  0x0007000E: KeyDisplay(
      label: 'k', category: KeyCategory.letter, page: 0x07, usageId: 0x0E),
  0x0007000F: KeyDisplay(
      label: 'l', category: KeyCategory.letter, page: 0x07, usageId: 0x0F),
  0x00070010: KeyDisplay(
      label: 'm', category: KeyCategory.letter, page: 0x07, usageId: 0x10),
  0x00070011: KeyDisplay(
      label: 'n', category: KeyCategory.letter, page: 0x07, usageId: 0x11),
  0x00070012: KeyDisplay(
      label: 'o', category: KeyCategory.letter, page: 0x07, usageId: 0x12),
  0x00070013: KeyDisplay(
      label: 'p', category: KeyCategory.letter, page: 0x07, usageId: 0x13),
  0x00070014: KeyDisplay(
      label: 'q', category: KeyCategory.letter, page: 0x07, usageId: 0x14),
  0x00070015: KeyDisplay(
      label: 'r', category: KeyCategory.letter, page: 0x07, usageId: 0x15),
  0x00070016: KeyDisplay(
      label: 's', category: KeyCategory.letter, page: 0x07, usageId: 0x16),
  0x00070017: KeyDisplay(
      label: 't', category: KeyCategory.letter, page: 0x07, usageId: 0x17),
  0x00070018: KeyDisplay(
      label: 'u', category: KeyCategory.letter, page: 0x07, usageId: 0x18),
  0x00070019: KeyDisplay(
      label: 'v', category: KeyCategory.letter, page: 0x07, usageId: 0x19),
  0x0007001A: KeyDisplay(
      label: 'w', category: KeyCategory.letter, page: 0x07, usageId: 0x1A),
  0x0007001B: KeyDisplay(
      label: 'x', category: KeyCategory.letter, page: 0x07, usageId: 0x1B),
  0x0007001C: KeyDisplay(
      label: 'y', category: KeyCategory.letter, page: 0x07, usageId: 0x1C),
  0x0007001D: KeyDisplay(
      label: 'z', category: KeyCategory.letter, page: 0x07, usageId: 0x1D),
  0x0007001E: KeyDisplay(
      label: '1', category: KeyCategory.number, page: 0x07, usageId: 0x1E),
  0x0007001F: KeyDisplay(
      label: '2', category: KeyCategory.number, page: 0x07, usageId: 0x1F),
  0x00070020: KeyDisplay(
      label: '3', category: KeyCategory.number, page: 0x07, usageId: 0x20),
  0x00070021: KeyDisplay(
      label: '4', category: KeyCategory.number, page: 0x07, usageId: 0x21),
  0x00070022: KeyDisplay(
      label: '5', category: KeyCategory.number, page: 0x07, usageId: 0x22),
  0x00070023: KeyDisplay(
      label: '6', category: KeyCategory.number, page: 0x07, usageId: 0x23),
  0x00070024: KeyDisplay(
      label: '7', category: KeyCategory.number, page: 0x07, usageId: 0x24),
  0x00070025: KeyDisplay(
      label: '8', category: KeyCategory.number, page: 0x07, usageId: 0x25),
  0x00070026: KeyDisplay(
      label: '9', category: KeyCategory.number, page: 0x07, usageId: 0x26),
  0x00070027: KeyDisplay(
      label: '0', category: KeyCategory.number, page: 0x07, usageId: 0x27),
  0x00070028: KeyDisplay(
      label: 'Enter',
      category: KeyCategory.edit,
      page: 0x07,
      usageId: 0x28,
      glyph: '⏎'),
  0x00070029: KeyDisplay(
      label: 'Esc',
      category: KeyCategory.edit,
      page: 0x07,
      usageId: 0x29,
      glyph: '⎋'),
  0x0007002A: KeyDisplay(
      label: 'Backspace',
      category: KeyCategory.edit,
      page: 0x07,
      usageId: 0x2A,
      glyph: '⌫'),
  0x0007002B: KeyDisplay(
      label: 'Tab',
      category: KeyCategory.edit,
      page: 0x07,
      usageId: 0x2B,
      glyph: '⇥'),
  0x0007002C: KeyDisplay(
      label: 'Space',
      category: KeyCategory.edit,
      page: 0x07,
      usageId: 0x2C,
      glyph: '␣'),
  0x0007002D: KeyDisplay(
      label: '-', category: KeyCategory.punctuation, page: 0x07, usageId: 0x2D),
  0x0007002E: KeyDisplay(
      label: '=', category: KeyCategory.punctuation, page: 0x07, usageId: 0x2E),
  0x0007002F: KeyDisplay(
      label: '[', category: KeyCategory.punctuation, page: 0x07, usageId: 0x2F),
  0x00070030: KeyDisplay(
      label: ']', category: KeyCategory.punctuation, page: 0x07, usageId: 0x30),
  0x00070031: KeyDisplay(
      label: '\\',
      category: KeyCategory.punctuation,
      page: 0x07,
      usageId: 0x31),
  0x00070033: KeyDisplay(
      label: ';', category: KeyCategory.punctuation, page: 0x07, usageId: 0x33),
  0x00070034: KeyDisplay(
      label: '\'',
      category: KeyCategory.punctuation,
      page: 0x07,
      usageId: 0x34),
  0x00070035: KeyDisplay(
      label: '`', category: KeyCategory.punctuation, page: 0x07, usageId: 0x35),
  0x00070036: KeyDisplay(
      label: ',', category: KeyCategory.punctuation, page: 0x07, usageId: 0x36),
  0x00070037: KeyDisplay(
      label: '.', category: KeyCategory.punctuation, page: 0x07, usageId: 0x37),
  0x00070038: KeyDisplay(
      label: '/', category: KeyCategory.punctuation, page: 0x07, usageId: 0x38),
  0x00070039: KeyDisplay(
      label: 'Caps Lock',
      category: KeyCategory.locking,
      page: 0x07,
      usageId: 0x39),
  0x0007003A: KeyDisplay(
      label: 'F1', category: KeyCategory.function, page: 0x07, usageId: 0x3A),
  0x0007003B: KeyDisplay(
      label: 'F2', category: KeyCategory.function, page: 0x07, usageId: 0x3B),
  0x0007003C: KeyDisplay(
      label: 'F3', category: KeyCategory.function, page: 0x07, usageId: 0x3C),
  0x0007003D: KeyDisplay(
      label: 'F4', category: KeyCategory.function, page: 0x07, usageId: 0x3D),
  0x0007003E: KeyDisplay(
      label: 'F5', category: KeyCategory.function, page: 0x07, usageId: 0x3E),
  0x0007003F: KeyDisplay(
      label: 'F6', category: KeyCategory.function, page: 0x07, usageId: 0x3F),
  0x00070040: KeyDisplay(
      label: 'F7', category: KeyCategory.function, page: 0x07, usageId: 0x40),
  0x00070041: KeyDisplay(
      label: 'F8', category: KeyCategory.function, page: 0x07, usageId: 0x41),
  0x00070042: KeyDisplay(
      label: 'F9', category: KeyCategory.function, page: 0x07, usageId: 0x42),
  0x00070043: KeyDisplay(
      label: 'F10', category: KeyCategory.function, page: 0x07, usageId: 0x43),
  0x00070044: KeyDisplay(
      label: 'F11', category: KeyCategory.function, page: 0x07, usageId: 0x44),
  0x00070045: KeyDisplay(
      label: 'F12', category: KeyCategory.function, page: 0x07, usageId: 0x45),
  0x00070046: KeyDisplay(
      label: 'Print Screen',
      category: KeyCategory.system,
      page: 0x07,
      usageId: 0x46),
  0x00070047: KeyDisplay(
      label: 'Scroll Lock',
      category: KeyCategory.locking,
      page: 0x07,
      usageId: 0x47),
  0x00070048: KeyDisplay(
      label: 'Pause', category: KeyCategory.system, page: 0x07, usageId: 0x48),
  0x00070049: KeyDisplay(
      label: 'Insert', category: KeyCategory.edit, page: 0x07, usageId: 0x49),
  0x0007004A: KeyDisplay(
      label: 'Home',
      category: KeyCategory.navigation,
      page: 0x07,
      usageId: 0x4A,
      glyph: '⇱'),
  0x0007004B: KeyDisplay(
      label: 'Page Up',
      category: KeyCategory.navigation,
      page: 0x07,
      usageId: 0x4B,
      glyph: '⇞'),
  0x0007004C: KeyDisplay(
      label: 'Delete',
      category: KeyCategory.edit,
      page: 0x07,
      usageId: 0x4C,
      glyph: '⌦'),
  0x0007004D: KeyDisplay(
      label: 'End',
      category: KeyCategory.navigation,
      page: 0x07,
      usageId: 0x4D,
      glyph: '⇲'),
  0x0007004E: KeyDisplay(
      label: 'Page Down',
      category: KeyCategory.navigation,
      page: 0x07,
      usageId: 0x4E,
      glyph: '⇟'),
  0x0007004F: KeyDisplay(
      label: 'Right',
      category: KeyCategory.navigation,
      page: 0x07,
      usageId: 0x4F,
      glyph: '→'),
  0x00070050: KeyDisplay(
      label: 'Left',
      category: KeyCategory.navigation,
      page: 0x07,
      usageId: 0x50,
      glyph: '←'),
  0x00070051: KeyDisplay(
      label: 'Down',
      category: KeyCategory.navigation,
      page: 0x07,
      usageId: 0x51,
      glyph: '↓'),
  0x00070052: KeyDisplay(
      label: 'Up',
      category: KeyCategory.navigation,
      page: 0x07,
      usageId: 0x52,
      glyph: '↑'),
  0x00070053: KeyDisplay(
      label: 'Num Lock',
      category: KeyCategory.locking,
      page: 0x07,
      usageId: 0x53),
  0x00070054: KeyDisplay(
      label: 'KP /', category: KeyCategory.numpad, page: 0x07, usageId: 0x54),
  0x00070055: KeyDisplay(
      label: 'KP *', category: KeyCategory.numpad, page: 0x07, usageId: 0x55),
  0x00070056: KeyDisplay(
      label: 'KP -', category: KeyCategory.numpad, page: 0x07, usageId: 0x56),
  0x00070057: KeyDisplay(
      label: 'KP +', category: KeyCategory.numpad, page: 0x07, usageId: 0x57),
  0x00070058: KeyDisplay(
      label: 'KP Enter',
      category: KeyCategory.numpad,
      page: 0x07,
      usageId: 0x58),
  0x00070059: KeyDisplay(
      label: 'KP 1', category: KeyCategory.numpad, page: 0x07, usageId: 0x59),
  0x0007005A: KeyDisplay(
      label: 'KP 2', category: KeyCategory.numpad, page: 0x07, usageId: 0x5A),
  0x0007005B: KeyDisplay(
      label: 'KP 3', category: KeyCategory.numpad, page: 0x07, usageId: 0x5B),
  0x0007005C: KeyDisplay(
      label: 'KP 4', category: KeyCategory.numpad, page: 0x07, usageId: 0x5C),
  0x0007005D: KeyDisplay(
      label: 'KP 5', category: KeyCategory.numpad, page: 0x07, usageId: 0x5D),
  0x0007005E: KeyDisplay(
      label: 'KP 6', category: KeyCategory.numpad, page: 0x07, usageId: 0x5E),
  0x0007005F: KeyDisplay(
      label: 'KP 7', category: KeyCategory.numpad, page: 0x07, usageId: 0x5F),
  0x00070060: KeyDisplay(
      label: 'KP 8', category: KeyCategory.numpad, page: 0x07, usageId: 0x60),
  0x00070061: KeyDisplay(
      label: 'KP 9', category: KeyCategory.numpad, page: 0x07, usageId: 0x61),
  0x00070062: KeyDisplay(
      label: 'KP 0', category: KeyCategory.numpad, page: 0x07, usageId: 0x62),
  0x00070063: KeyDisplay(
      label: 'KP .', category: KeyCategory.numpad, page: 0x07, usageId: 0x63),
  0x00070065: KeyDisplay(
      label: 'Menu', category: KeyCategory.system, page: 0x07, usageId: 0x65),
  0x00070066: KeyDisplay(
      label: 'Power', category: KeyCategory.system, page: 0x07, usageId: 0x66),
  0x00070067: KeyDisplay(
      label: 'KP =', category: KeyCategory.numpad, page: 0x07, usageId: 0x67),
  0x00070068: KeyDisplay(
      label: 'F13', category: KeyCategory.function, page: 0x07, usageId: 0x68),
  0x00070069: KeyDisplay(
      label: 'F14', category: KeyCategory.function, page: 0x07, usageId: 0x69),
  0x0007006A: KeyDisplay(
      label: 'F15', category: KeyCategory.function, page: 0x07, usageId: 0x6A),
  0x0007006B: KeyDisplay(
      label: 'F16', category: KeyCategory.function, page: 0x07, usageId: 0x6B),
  0x0007006C: KeyDisplay(
      label: 'F17', category: KeyCategory.function, page: 0x07, usageId: 0x6C),
  0x0007006D: KeyDisplay(
      label: 'F18', category: KeyCategory.function, page: 0x07, usageId: 0x6D),
  0x0007006E: KeyDisplay(
      label: 'F19', category: KeyCategory.function, page: 0x07, usageId: 0x6E),
  0x0007006F: KeyDisplay(
      label: 'F20', category: KeyCategory.function, page: 0x07, usageId: 0x6F),
  0x00070070: KeyDisplay(
      label: 'F21', category: KeyCategory.function, page: 0x07, usageId: 0x70),
  0x00070071: KeyDisplay(
      label: 'F22', category: KeyCategory.function, page: 0x07, usageId: 0x71),
  0x00070072: KeyDisplay(
      label: 'F23', category: KeyCategory.function, page: 0x07, usageId: 0x72),
  0x00070073: KeyDisplay(
      label: 'F24', category: KeyCategory.function, page: 0x07, usageId: 0x73),
  0x000700E0: KeyDisplay(
      label: 'Ctrl', category: KeyCategory.modifier, page: 0x07, usageId: 0xE0),
  0x000700E1: KeyDisplay(
      label: 'Shift',
      category: KeyCategory.modifier,
      page: 0x07,
      usageId: 0xE1,
      glyph: '⇧'),
  0x000700E2: KeyDisplay(
      label: 'Alt', category: KeyCategory.modifier, page: 0x07, usageId: 0xE2),
  0x000700E3: KeyDisplay(
      label: 'GUI', category: KeyCategory.modifier, page: 0x07, usageId: 0xE3),
  0x000700E4: KeyDisplay(
      label: 'Right Ctrl',
      category: KeyCategory.modifier,
      page: 0x07,
      usageId: 0xE4),
  0x000700E5: KeyDisplay(
      label: 'Right Shift',
      category: KeyCategory.modifier,
      page: 0x07,
      usageId: 0xE5,
      glyph: '⇧'),
  0x000700E6: KeyDisplay(
      label: 'Right Alt',
      category: KeyCategory.modifier,
      page: 0x07,
      usageId: 0xE6),
  0x000700E7: KeyDisplay(
      label: 'Right GUI',
      category: KeyCategory.modifier,
      page: 0x07,
      usageId: 0xE7),
  0x000C00B5: KeyDisplay(
      label: 'Next Track',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0xB5,
      icon: Icons.skip_next),
  0x000C00B6: KeyDisplay(
      label: 'Prev Track',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0xB6,
      icon: Icons.skip_previous),
  0x000C00B7: KeyDisplay(
      label: 'Stop',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0xB7,
      icon: Icons.stop),
  0x000C00B8: KeyDisplay(
      label: 'Eject', category: KeyCategory.media, page: 0x0C, usageId: 0xB8),
  0x000C00CD: KeyDisplay(
      label: 'Play/Pause',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0xCD,
      icon: Icons.play_arrow),
  0x000C00E0: KeyDisplay(
      label: 'Volume', category: KeyCategory.media, page: 0x0C, usageId: 0xE0),
  0x000C00E1: KeyDisplay(
      label: 'Balance', category: KeyCategory.media, page: 0x0C, usageId: 0xE1),
  0x000C00E2: KeyDisplay(
      label: 'Mute',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0xE2,
      icon: Icons.volume_off),
  0x000C00E9: KeyDisplay(
      label: 'Volume Up',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0xE9,
      icon: Icons.volume_up),
  0x000C00EA: KeyDisplay(
      label: 'Volume Down',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0xEA,
      icon: Icons.volume_down),
  0x000C0192: KeyDisplay(
      label: 'Calculator',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0x192),
  0x000C01A0: KeyDisplay(
      label: 'Email', category: KeyCategory.media, page: 0x0C, usageId: 0x1A0),
  0x000C0223: KeyDisplay(
      label: 'Browser Search',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0x223),
  0x000C0224: KeyDisplay(
      label: 'Home Page',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0x224),
  0x000C0225: KeyDisplay(
      label: 'Browser Back',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0x225),
  0x000C0226: KeyDisplay(
      label: 'Browser Forward',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0x226),
  0x000C0227: KeyDisplay(
      label: 'Browser Stop',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0x227),
  0x000C0228: KeyDisplay(
      label: 'Refresh',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0x228),
  0x000C0229: KeyDisplay(
      label: 'Bookmarks',
      category: KeyCategory.media,
      page: 0x0C,
      usageId: 0x229),
  0x000C022A: KeyDisplay(
      label: 'Find', category: KeyCategory.media, page: 0x0C, usageId: 0x22A),
};
