// Mocks generated by Mockito 5.4.6 from annotations
// in awesome_studio_pedal/test/widget/upload_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:awesome_studio_pedal/models/upload_result.dart' as _i2;
import 'package:awesome_studio_pedal/services/ble_service.dart' as _i4;
import 'package:awesome_studio_pedal/services/schema_service.dart' as _i3;
import 'package:flutter_blue_plus/flutter_blue_plus.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUploadResult_0 extends _i1.SmartFake implements _i2.UploadResult {
  _FakeUploadResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValidationResult_1 extends _i1.SmartFake
    implements _i3.ValidationResult {
  _FakeValidationResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleService extends _i1.Mock implements _i4.BleService {
  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Stream<String> get statusStream => (super.noSuchMethod(
        Invocation.getter(#statusStream),
        returnValue: _i5.Stream<String>.empty(),
        returnValueForMissingStub: _i5.Stream<String>.empty(),
      ) as _i5.Stream<String>);

  @override
  _i5.Stream<_i6.BluetoothAdapterState> get adapterState => (super.noSuchMethod(
        Invocation.getter(#adapterState),
        returnValue: _i5.Stream<_i6.BluetoothAdapterState>.empty(),
        returnValueForMissingStub:
            _i5.Stream<_i6.BluetoothAdapterState>.empty(),
      ) as _i5.Stream<_i6.BluetoothAdapterState>);

  @override
  _i6.BluetoothAdapterState get adapterStateNow => (super.noSuchMethod(
        Invocation.getter(#adapterStateNow),
        returnValue: _i6.BluetoothAdapterState.unknown,
        returnValueForMissingStub: _i6.BluetoothAdapterState.unknown,
      ) as _i6.BluetoothAdapterState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<bool> hasBlePermissions() => (super.noSuchMethod(
        Invocation.method(
          #hasBlePermissions,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestBlePermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestBlePermissions,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isBlePermissionPermanentlyDenied() => (super.noSuchMethod(
        Invocation.method(
          #isBlePermissionPermanentlyDenied,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i6.ScanResult>> scan(
          {Duration? timeout = const Duration(seconds: 10)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #scan,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i5.Future<List<_i6.ScanResult>>.value(<_i6.ScanResult>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i6.ScanResult>>.value(<_i6.ScanResult>[]),
      ) as _i5.Future<List<_i6.ScanResult>>);

  @override
  _i5.Future<void> connect(_i6.BluetoothDevice? device) => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [device],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void disconnect() => super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.UploadResult> uploadProfiles(String? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfiles,
          [json],
        ),
        returnValue: _i5.Future<_i2.UploadResult>.value(_FakeUploadResult_0(
          this,
          Invocation.method(
            #uploadProfiles,
            [json],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.UploadResult>.value(_FakeUploadResult_0(
          this,
          Invocation.method(
            #uploadProfiles,
            [json],
          ),
        )),
      ) as _i5.Future<_i2.UploadResult>);

  @override
  _i5.Future<_i2.UploadResult> uploadConfig(String? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadConfig,
          [json],
        ),
        returnValue: _i5.Future<_i2.UploadResult>.value(_FakeUploadResult_0(
          this,
          Invocation.method(
            #uploadConfig,
            [json],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.UploadResult>.value(_FakeUploadResult_0(
          this,
          Invocation.method(
            #uploadConfig,
            [json],
          ),
        )),
      ) as _i5.Future<_i2.UploadResult>);

  @override
  _i5.Future<String?> readDeviceHardware() => (super.noSuchMethod(
        Invocation.method(
          #readDeviceHardware,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> readDeviceFirmwareVersion() => (super.noSuchMethod(
        Invocation.method(
          #readDeviceFirmwareVersion,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SchemaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSchemaService extends _i1.Mock implements _i3.SchemaService {
  @override
  _i5.Future<_i3.ValidationResult> validateProfiles(
          Map<String, dynamic>? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateProfiles,
          [json],
        ),
        returnValue:
            _i5.Future<_i3.ValidationResult>.value(_FakeValidationResult_1(
          this,
          Invocation.method(
            #validateProfiles,
            [json],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.ValidationResult>.value(_FakeValidationResult_1(
          this,
          Invocation.method(
            #validateProfiles,
            [json],
          ),
        )),
      ) as _i5.Future<_i3.ValidationResult>);

  @override
  _i5.Future<_i3.ValidationResult> validateConfig(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateConfig,
          [json],
        ),
        returnValue:
            _i5.Future<_i3.ValidationResult>.value(_FakeValidationResult_1(
          this,
          Invocation.method(
            #validateConfig,
            [json],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.ValidationResult>.value(_FakeValidationResult_1(
          this,
          Invocation.method(
            #validateConfig,
            [json],
          ),
        )),
      ) as _i5.Future<_i3.ValidationResult>);
}
