// Mocks generated by Mockito 5.4.6 from annotations
// in awesome_studio_pedal/test/widget/validation_banner_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:awesome_studio_pedal/services/schema_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValidationResult_0 extends _i1.SmartFake
    implements _i2.ValidationResult {
  _FakeValidationResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SchemaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSchemaService extends _i1.Mock implements _i2.SchemaService {
  @override
  _i3.Future<_i2.ValidationResult> validateProfiles(
          Map<String, dynamic>? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateProfiles,
          [json],
        ),
        returnValue:
            _i3.Future<_i2.ValidationResult>.value(_FakeValidationResult_0(
          this,
          Invocation.method(
            #validateProfiles,
            [json],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.ValidationResult>.value(_FakeValidationResult_0(
          this,
          Invocation.method(
            #validateProfiles,
            [json],
          ),
        )),
      ) as _i3.Future<_i2.ValidationResult>);

  @override
  _i3.Future<_i2.ValidationResult> validateConfig(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateConfig,
          [json],
        ),
        returnValue:
            _i3.Future<_i2.ValidationResult>.value(_FakeValidationResult_0(
          this,
          Invocation.method(
            #validateConfig,
            [json],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.ValidationResult>.value(_FakeValidationResult_0(
          this,
          Invocation.method(
            #validateConfig,
            [json],
          ),
        )),
      ) as _i3.Future<_i2.ValidationResult>);
}
