#!/usr/bin/env python3
"""Generate `app/lib/constants/hid_display_table.dart`.

Inputs (under scripts/hid_display_data/):
  - keyboard_keypad_0x07.yaml — usage_id → label/category for HID page 0x07.
  - consumer_0x0c.yaml — usage_id → label/category for HID page 0x0C.
  - overlay.yaml — hand-maintained glyph/icon/label overrides keyed by
    "<page>:<usage_id>".

Output:
  - app/lib/constants/hid_display_table.dart — `kHidUsageDisplay` const map.

Idempotency: regenerating without changing inputs produces an identical file
(no timestamps, no nondeterministic ordering). The Dart unit test relies on
this.

Usage:
  python scripts/generate_hid_display_table.py
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
DATA_DIR = REPO / "scripts" / "hid_display_data"
OUT = REPO / "app" / "lib" / "constants" / "hid_display_table.dart"

CATEGORIES = (
    "letter",
    "number",
    "navigation",
    "edit",
    "modifier",
    "function",
    "punctuation",
    "system",
    "media",
    "locking",
    "numpad",
    "language",
)


def _load(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _packed_key(page: int, usage_id: int) -> int:
    """Pack page (high 16 bits) + usage_id (low 16 bits) into a 32-bit int.

    The Live-keystroke page receives Flutter `KeyEvent`s whose
    `physicalKey.usbHidUsage` is already in this packed form
    (see Flutter's `PhysicalKeyboardKey`), so the map key matches.
    """
    return (page << 16) | usage_id


def _dart_str(s: str) -> str:
    """Dart string literal — single-quoted, escape backslash and single quote."""
    return "'" + s.replace("\\", "\\\\").replace("'", r"\'") + "'"


def main() -> None:
    page_07 = _load(DATA_DIR / "keyboard_keypad_0x07.yaml")
    page_0c = _load(DATA_DIR / "consumer_0x0c.yaml")
    overlay = _load(DATA_DIR / "overlay.yaml")

    entries: dict[int, dict] = {}

    for usage_id, data in sorted(page_07.items()):
        entries[_packed_key(0x07, int(usage_id))] = {
            "label": data["label"],
            "category": data["category"],
            "glyph": None,
            "icon": None,
            "page": 0x07,
            "usageId": int(usage_id),
        }

    for usage_id, data in sorted(page_0c.items()):
        entries[_packed_key(0x0C, int(usage_id))] = {
            "label": data["label"],
            "category": data["category"],
            "glyph": None,
            "icon": None,
            "page": 0x0C,
            "usageId": int(usage_id),
        }

    for key, data in (overlay or {}).items():
        page_str, usage_str = key.split(":")
        page = int(page_str, 0)
        usage_id = int(usage_str, 0)
        packed = _packed_key(page, usage_id)
        if packed not in entries:
            raise SystemExit(
                f"overlay.yaml references {key} but no base entry exists"
            )
        entry = entries[packed]
        if "label" in data:
            entry["label"] = data["label"]
        if "glyph" in data:
            entry["glyph"] = data["glyph"]
        if "icon" in data:
            entry["icon"] = data["icon"]

    lines: list[str] = []
    lines.append(
        "// GENERATED by scripts/generate_hid_display_table.py — do not edit by hand."
    )
    lines.append("// Re-run the generator after editing scripts/hid_display_data/*.yaml.")
    lines.append("")
    lines.append("import 'package:flutter/material.dart';")
    lines.append("")
    lines.append("/// HID usage page + ID → display descriptor for keystroke chips.")
    lines.append("enum KeyCategory {")
    for cat in CATEGORIES:
        lines.append(f"  {cat},")
    lines.append("}")
    lines.append("")
    lines.append("class KeyDisplay {")
    lines.append("  const KeyDisplay({")
    lines.append("    required this.label,")
    lines.append("    required this.category,")
    lines.append("    required this.page,")
    lines.append("    required this.usageId,")
    lines.append("    this.glyph,")
    lines.append("    this.icon,")
    lines.append("  });")
    lines.append("")
    lines.append("  final String label;")
    lines.append("  final KeyCategory category;")
    lines.append("  final int page;")
    lines.append("  final int usageId;")
    lines.append("  final String? glyph;")
    lines.append("  final IconData? icon;")
    lines.append("}")
    lines.append("")
    lines.append("/// Packed (page << 16) | usageId → display descriptor.")
    lines.append("/// Same packing as Flutter's PhysicalKeyboardKey.usbHidUsage.")
    lines.append("const Map<int, KeyDisplay> kHidUsageDisplay = {")

    for packed in sorted(entries):
        e = entries[packed]
        parts = [
            f"label: {_dart_str(str(e['label']))}",
            f"category: KeyCategory.{e['category']}",
            f"page: 0x{e['page']:02X}",
            f"usageId: 0x{e['usageId']:02X}",
        ]
        if e["glyph"] is not None:
            parts.append(f"glyph: {_dart_str(e['glyph'])}")
        if e["icon"] is not None:
            parts.append(f"icon: Icons.{e['icon']}")
        joined = ", ".join(parts)
        lines.append(f"  0x{packed:08X}: KeyDisplay({joined}),")

    lines.append("};")
    lines.append("")

    out_text = "\n".join(lines)
    OUT.parent.mkdir(parents=True, exist_ok=True)

    # Pre-format via `dart format` if available so the committed file
    # matches the pre-commit hook's expectation. Without this, every
    # regen would dirty the file relative to the formatter.
    dart = shutil.which("dart")
    if dart is not None:
        # Write to a temp path inside the same dir, format it, read back.
        tmp = OUT.with_suffix(".dart.tmp")
        tmp.write_text(out_text, encoding="utf-8")
        subprocess.run([dart, "format", "--output=write", str(tmp)], check=True)
        formatted = tmp.read_text(encoding="utf-8")
        tmp.unlink()
        out_text = formatted

    if OUT.exists() and OUT.read_text(encoding="utf-8") == out_text:
        print(f"hid_display_table: {OUT.relative_to(REPO)} already up to date.")
        return
    OUT.write_text(out_text, encoding="utf-8")
    print(f"hid_display_table: wrote {OUT.relative_to(REPO)} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
