#include "config.h"
#include "builder_config.h"

/**
 * @brief Hardware configuration for Adafruit Feather nRF52840 Express
 *
 * Constructed from builder_config.h. Edit that file to change pin
 * assignments or counts — do not edit this file directly.
 */
const HardwareConfig hardwareConfig = {
    CONF_NUM_PROFILES,
    CONF_NUM_SELECT_LEDS,
    CONF_NUM_BUTTONS,
    CONF_LED_BLUETOOTH,
    CONF_LED_POWER,
    {CONF_LED_SELECT[0], CONF_LED_SELECT[1], CONF_LED_SELECT[2], 0, 0, 0},
    CONF_BUTTON_SELECT,
    {CONF_BUTTON_PINS[0],
     CONF_BUTTON_PINS[1],
     CONF_BUTTON_PINS[2],
     CONF_BUTTON_PINS[3],
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0}};
